##**Vector**

In [2]:
import numpy as np

In [5]:
x = [1, 7, 2]
print(x)
x = np.array([1, 7, 2])
print(x)

[1, 7, 2]
[1 7 2]


In [7]:
x = np.array([1, 7, 2])
y = np.array([5, 2, 1])

In [8]:
x + y

array([6, 9, 3])

In [9]:
x - y

array([-4,  5,  1])

In [10]:
x * y

array([ 5, 14,  2])

In [13]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

def l2_norm(x):     # = np.linalg.norm
    x_norm = x * x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

In [17]:
x = np.array([-1, 2, -3])

l1_norm(x)

6

In [18]:
x = np.array([-6, -8])

l2_norm(x)

10.0

In [23]:
x = np.array([-3, 0])
y = np.array([0, 4])

print(l2_norm(x-y))

5.0


In [26]:
x = np.array([0, 1])
y = np.array([0, 2])

print(l2_norm(x-y))

1.0


In [27]:
def angle(x, y):
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

In [28]:
x = np.array([0, 1])
y = np.array([0, 2])

angle(x, y)

0.0