##**Matrix**

In [3]:
import numpy as np

In [5]:
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

In [6]:
x @ y       # 행렬 곱셈

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [8]:
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

y = np.array([[0, 1, -1], [1, -1, 0]])

In [9]:
np.inner(x, y)      # 내적 계산

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

In [ ]:
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

In [10]:
np.linalg.inv(x)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [11]:
x @ np.linalg.inv(x)    # 역행렬

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00, -5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [12]:
y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

In [13]:
np.linalg.pinv(y)

array([[ 5.00000000e-01,  4.09730229e-17, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [14]:
np.linalg.pinv(y) @ y       # 유사 역행렬

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00]])