##**Numpy**

In [1]:
coefficient_matrix = [[2, 2, 1], [2, -1, 2], [1, -1, 2]]
constant_vector = [9, 6, 5]

In [2]:
import numpy as np

test_array = np.array([1, 4, 5, 8], float)

print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [3]:
test_array = np.array([1, 4, 5, "8"], float)        # String Type의 데이터를 입력해도

print(test_array)
print(type(test_array))                             # Float Type으로 자동 형변환을 실시
print(test_array.dtype)                             # Array(배열) 전체의 데이터 Type을 반환함
print(test_array.shape)                             # Array(배열) 의 shape을 반환함

[1. 4. 5. 8.]
<class 'numpy.ndarray'>
float64
(4,)


#####Array shape (vector)

In [4]:
test_array = np.array([1, 4, 5, "8"], float)
test_array

array([1., 4., 5., 8.])

#####Array shape (matrix)

In [5]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [6]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]

np.array(tensor, int).shape

(4, 3, 4)

#####Array shape - ndim & size

In [7]:
np.array(tensor, int).ndim

3

In [8]:
np.array(tensor, int).size

48

#####Array dtype

In [9]:
np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.array([[1, 2, 3],[4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [11]:
np.array([[1, 2, 3],[4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [12]:
np.array([[1, 2, 3],[4.5, "5", "6"]], dtype=np.int8).nbytes

6

In [13]:
np.array([[1, 2, 3],[4.5, "5", "6"]], dtype=np.float64).nbytes

48

##**Handling Shape**

#####Reshape

In [14]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [15]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [16]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [17]:
np.array(test_matrix).reshape(2, 4).shape

(2, 4)

In [18]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [19]:
np.array(test_matrix).reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

#####flatten

In [20]:
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

##**Indexing & Slicing**

#####indexing

In [21]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)

# List와 달리 이차원 배열에서 [0, 0]과 같은 표기법을 제공함
print(a)
print(a[0, 0])
print(a[0][0])

a[0, 0] = 12
print(a)

a[0][0] = 5
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


In [22]:
test_example = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
test_example[0][0]

1

In [24]:
test_example[0, 0]

1

In [25]:
test_example[0, 0] = 12     # Matrix 0, 0 에 12 할당
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [26]:
test_example[0][0] = 5      # Matrix 0, 0 에 12 할당
test_example[0, 0]

5

#####slicing

In [27]:
# List와 달리 행과 열 부분을 나눠서 slicing이 가능함

a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], int)

print(a[:,2:])     # 전체 Row의 2열 이상
print(a[1,1:3])    # 1 Row의 1열 ~ 2열
print(a[1:3])      # 1 Row ~ 2Row의 전체

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [28]:
test_example = np.array([[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)
test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [29]:
test_example[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [30]:
test_example[1,:2]

array([1, 2])

In [31]:
test_example = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_example[:,2:]      # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [32]:
test_example[1,1:3]     # 1 Row의 1열 ~ 2열

array([7, 8])

In [33]:
test_example[1:3]        # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

##**Creation Function**

#####arange

In [34]:
np.arange(30)   # range: List의 range와 같은 효과, integer로 0부터 29까지 요소 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
np.arange(0, 5, 0.5)    # floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [36]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#####ones, zeros and empty

In [37]:
np.zeros(shape=(10,), dtype=np.int8)     # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [38]:
np.zeros((2, 5))        # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [40]:
np.ones((2, 5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [41]:
np.empty(shape=(10,), dtype=np.int8)

array([ -32, -107,   55, -117,  -17,   85,    0,    0,    0,    0],
      dtype=int8)

In [42]:
np.empty((3, 5))

array([[4.66829471e-310, 1.06099790e-312, 1.01855798e-312,
        9.54898106e-313, 1.16709769e-312],
       [1.01855798e-312, 1.23075756e-312, 1.03977794e-312,
        1.01855798e-312, 9.76118064e-313],
       [1.03977794e-312, 1.12465777e-312, 1.12465777e-312,
        4.44659081e-322, 0.00000000e+000]])

#####something_like

In [43]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [44]:
test_matrix = np.arange(30).reshape(5, 6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#####identity

- 단위 행렬(i 행렬)생성

In [45]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [46]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#####eye

- 대각선이 1인 행렬, k값의 시작 index변경이 가능

In [47]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.eye(3, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [50]:
np.eye(3, 5, k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

#####diag

- 대각 행렬의 값을 추출

In [51]:
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])

In [52]:
np.diag(matrix, k=1)

array([1, 5])

In [53]:
# 데이터 분포에 따른 sampling으로 array를 생성

np.random.uniform(0, 1, 10).reshape(2, 5)       # 균등 분포

array([[0.9064801 , 0.06379094, 0.09790705, 0.08720189, 0.26196143],
       [0.68476656, 0.89349203, 0.41051184, 0.89386669, 0.68807412]])

In [54]:
np.random.normal(0, 1, 10).reshape(2, 5)        # 정규 분포

array([[ 0.59538992, -0.81154652,  0.03077652, -1.81944532,  1.76456948],
       [ 0.53927957, -0.71121397, -0.41619678,  1.14643253, -1.62102172]])

##**Operation functions**

#####sum

In [55]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# ndarray의 elemet들 간의 합을 수함, list의 sum 기능과 동일

test_array.sum(dtype=np.float16)

55.0

#####axis

In [57]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [59]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [60]:
print(third_order_tensor.sum(axis=0))

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]


In [61]:
print(third_order_tensor.sum(axis=1))

[[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]


In [62]:
print(third_order_tensor.sum(axis=2))

[[10 26 42]
 [10 26 42]
 [10 26 42]]


#####mean & std

In [63]:
# ndarray의 element들 간의 평균 또는 표준 편차를 반환

test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [65]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

#####Mathmatical functions

In [66]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

#####concatenate

- Numpy array를 합치는 함수

In [67]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [68]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.hstack((a, b))

array([1, 2, 3, 2, 3, 4])

In [69]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [70]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

##**Array Operation**

- Opertaion b/t arrays

In [71]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [72]:
test_a + test_a     # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [73]:
test_a - test_a     # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
test_a * test_a     # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

#####Element-wise operations

- Array간 shape이 같을 떄 일어나는 연산

In [75]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

#####Dot product

In [76]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)
print(test_a, '\n\n', test_b)

[[1 2 3]
 [4 5 6]] 

 [[ 7  8]
 [ 9 10]
 [11 12]]


In [77]:
# 행렬의 기본 연산 (행렬곱)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

#####transpose

In [78]:
test_a = np.arange(1, 7).reshape(2, 3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [81]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#####broadcasting

- shape이 다른 배열 간 연산을 지원하는 기능

In [82]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [83]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [84]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [85]:
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [86]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [87]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [88]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

- broadcasting : vector-matrix 연산

In [89]:
test_matrix = np.arange(1, 13). reshape(4, 3)
print(test_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [90]:
test_vector = np.arange(10, 40, 10)
print(test_vector)

[10 20 30]


In [91]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

#####Numpy performance #1

In [92]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar*value)
    return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

# timeit : jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수
%timeit scalar_vector_product(scalar, vector)   # for loop를 이용한 성능
%timeit [scalar * value for value in range(iternation_max)]     # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar      # numpy를 이용한 성능

1 loop, best of 5: 14.3 s per loop
1 loop, best of 5: 12.4 s per loop
1 loop, best of 5: 261 ms per loop


**for loop < list cimprehension < numpy**

##**Comparisons**

- All & Any

In [93]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.any(a>5), np.any(a<0)    # any : 하나라도 조건에 만족한다면 true

(True, False)

In [95]:
np.all(a>5), np.all(a<10)   # all : 모두가 조건에 만족한다면 true

(False, True)

#####Comparison Operation #1

In [96]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [97]:
test_a == test_b

array([False, False, False])

In [98]:
(test_a > test_b).any()     # any: 하나라도 True라면 Ture

True

#####Comparison Operation #2

In [99]:
a = np.array([1, 3, 0], float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [100]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [101]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

#####np.where

In [102]:
np.where(a > 0,3,2)

array([3, 3, 2])

In [103]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9]),)

In [107]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)     # Not a Number

array([False,  True, False])

In [108]:
np.isfinite(a)      # 유한수 판단

array([ True, False, False])

#####argmax & argmin

In [110]:
# array내 최대값 또는 최소값의 index를 반환함
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

In [111]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

##**boolean & fancy index**

In [113]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [114]:
test_array[test_array > 3]      # 조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [115]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

#####boolean index

In [117]:
A = np.array([[12, 13, 14, 12, 16, 14, 11, 10, 9],
              [11, 14, 12, 15, 15, 16, 10, 12, 11],
              [10, 12, 12, 15, 14, 16, 10, 12, 12]])

B = A < 15
B.astype(np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1]])

#####fancy index

In [118]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)       # 반드시 integer로 선언
a[b]        # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [119]:
a.take(b)       # take 함수: bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [120]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]      # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

##**numpy data i/o**

#####loadtxt & savetxt

In [122]:
from google.colab import drive
drive.mount('/content/gdrive')

file_path = "/content/gdrive/MyDrive/Colab Notebooks/Reference/populations.txt"

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [123]:
a = np.loadtxt(file_path)     # 파일 호출
a[:10]

array([[ 19000., 320000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,   7020.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.]])

In [124]:
a_int = a.astype(int)
a_int[:3]

array([[ 19000, 320000,   4000,  48300],
       [  1901,  47200,   6100,  48200],
       [  1902,   7020,   9800,  41500]])

In [125]:
np.savetxt('int_data.csv', a_int, delimiter=",")        # int_data.csv로 저장

#####numpy object - npy

In [128]:
np.save("npy_test", arr=a_int)

In [129]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([[ 19000, 320000,   4000,  48300],
       [  1901,  47200,   6100,  48200],
       [  1902,   7020,   9800,  41500]])